baseURL = "https://dariaserkova.github.io"
languageCode = "en-us"
theme = "aafu"
enableGitInfo = "true"

[params]
    title = "Daria Serkova"
    author = "Daria Serkova"
    description = "my page ^_^"
    copyright = 'powered by <a href="https://gohugo.io/">hugo</a>'

    [params.theme]
        allowToggle = true
        mainTheme = "light"
        altTheme = "dark"

    [params.favicons]
        use = false
        metas = ''

    # Profile section
    [params.profile]
        name = "Daria Serkova"
		tagline = "Systems Engineer"
		location = "Saint-Petersburg, Russia"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"
        [[params.social.list]]
            class = "fab"
            icon = "fas fa-envelope"
            url = "mailto:miss.dariaserkova@yandex.ru"
            title = "Email"
        [[params.social.list]]
            class = "fab"
            icon = "fab fa-telegram-plane"
            url = "https://t.me/dariaserkova"
            title = "Telegram"
        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/daria-serkova-a431b081"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-stack-overflow"
            url = "https://stackoverflow.com/users/story/10749628"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/dariaserkova"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fas fa-file-pdf"
            url = "docs/dserkova_cv.pdf"
            title = "PDF"
		

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-smile-beam"
        description = '''10+ years experience in maintenance, deploy automation and monitoring realisation of 
        different kinds of applications, in automating software life cycle using different set of tools, 
        great experience of communicating with customer and dev teams. I like the ideas of infrastructure as code, cloud computing 
        and DevOps principles and try to behave in accordance with them. Speaking about tools I like python, golang, kubernetes
        and try be be aware of it.       
        '''
        

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"
        [[params.experience.list]]
            position = "DevOps TeamLead"
            dates = "Jun 2022 - Present"
            company = "Luchi (BestDoctor), Remote, Russia"
            details = "Lead of DevOps and infrastructure team, responsible for all production and non-production environments, increased teammemmbers from 3 to 8, organized duty shifts, developed and presented the strategy of the department, made regular digests about the team's work for other departments, represent the department on company all-hands, took care of the atmosphere and the mood of the team"        
        [[params.experience.list]]
            position = "DevOps Engineer in Core Team"
            dates = "May 2021 - Jun 2022"
            company = "Arrival, Saint-Petersburg, Russia"
            details = "Maintained core clusterised platform of the company, developed cluster-on-demand vendor agnostic system, k8s operator to provide environments on-demand, developed custom terraform modelues for different projects, start developing cloud-agnostic k8s installations with kubernetes cluster api, participated in supporting and consulting of dev and ops teams"
        [[params.experience.list]]
            position = "Senior Systems Engineer"
            dates = "Feb. 2020 - May 2021"
            company = "Wrike, Saint-Petersburg, Russia"
            details = "Maintained production and stage environments (k8s clusters and non-dockerized applications), prepared and deployed cloud infrastructure as code, developed and support custom packages builds and monitoring schemas, participated in team's on-call routines and maintenance, performed automatization of a variety of workflows. "
        [[params.experience.list]]
            position = "Senior Engineer of Infrastructure Team"
            dates = "Nov. 2018 - Jan. 2020"
            company = "Tinkoff Bank (TCS Group), Saint-Petersburg, Russia"
            details = "Researched and made important architecture decisions such as the choice of orchestrator, deploy strategy, infrastructure type. Participated in division of 'monolith' to container environment, supported QA and DEV teams with CI/CD processes and infrastructure issues, organized continuous maintenance and monitoring alerting of developing and production environments"
        [[params.experience.list]]
            position = "Senior Systems Engineer"
            dates = "Sep. 2017 - Nov. 2018"
            details = "Automated deploy, build and some of QA processes for a bunch of applications. Came up with and performed a way to manipulate CI/CD infrastructure as a code: store it in VCS, test it, and see when, which changes and by whom were made. Participated in applications' migration to the cloud."
            company = "EPAM Systems, Saint-Petersburg, Russia"
        [[params.experience.list]]
            position = "Senior Application Administrator"
            dates = "Aug. 2014 - Aug. 2017"
            details = "Automated deploy process, organized the preproduction application testing, controlled and designed monitoring algorithms, supervised technical support engineers"
            company = "I-Digital, Saint-Petersburg, Russia"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Specialist"
            college = "Saint-Petersburg State University of Engeneering and Economics"
            dates = "Jun. 2008 - Aug. 2013"
            thesis_title = "Information Systems and Technology in Economy"

        [params.project]
        title = "Tools"
        icon = "fas fa-toolbox"

        [[params.project.list]]
            title = "Terraform"
            url = "https://www.terraform.io/"
            description = "Infrastructure in AWS, GCP, Azure Snowflake, YandexCloud"
        [[params.project.list]]
            title = "Kubernetes"
            description = "Vendor agnostic k8s clusters, k8s operators for business needs, VPA, HPA"
        [[params.project.list]]
            title = "Gitlab CI"
            url = "https://docs.gitlab.com/ee/ci"
            description = "Automation of releases and infrustructure packages building, api with python, different types of runners/builders"
        [[params.project.list]]
            title = "DB clusters"
            description = "clickhouse (on premise, k8s + operator), postgres (patroni, pgbouncer, k8s operator)"
        [[params.project.list]]
            title = "Cloud computing"
            description = "AWS, Selectel, YandexCloud, GCP, Azure"
        [[params.project.list]]
            title = "Ansible"
            url = "https://www.ansible.com"
            description = "Automation of deploy anything anywhere: application, LB-s, infrastructure parts etc. Custom modules. Different kinds of templates for specific purposes"
        [[params.project.list]]
            title = "Containers"
            description = "Custom docker build for self-written and opensource applications. Orchestration. Monitoring." 
        [[params.project.list]]
            title = "Monitoring, visualisation, alerting"
            description = "Prometheus (exporters, PomQL for specific computing, alertmanager), Grafana, Kibana, Zabbix"
        [[params.project.list]]
            title = "Jenkins"
            url = "https://jenkins.io"
            description = "Groovy DSL, Jenkins pipelines, Jenkins api with python"
        [[params.project.list]]
            title = "Languages & Operating Systems"
            description = "Python, bash, golang, lua, deb- and rpm-based linux"
        [[params.project.list]]
            title = "Log management"
            description = "Graylog, fluentd, loki, ELK"

    
    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Infrastructure as Code"
            skillrating = 85
        [[params.skill.list]]
            skill = "Kubernetes"
            skillrating = 70
        [[params.skill.list]]
            skill = "CI/CD automation"
            skillrating = 75
        [[params.skill.list]]
            skill = "Administration"
            skillrating = 75
        [[params.skill.list]]
            skill = "Script writing"
            skillrating = 85
        [[params.skill.list]]
            skill = "Monitoring/Troubleshooting"
            skillrating = 90
        [[params.skill.list]]
            skill = "Mentoring"
            skillrating = 80
        [[params.skill.list]]
            skill = "Customer & developer Support"
            skillrating = 90
        [[params.skill.list]]
            skill = "DevOps"
            skillrating = 80

    [params.publication]
    title = "Read list"
    icon = "fas fa-book"
    #The order below determines the order in which the items appear in "Publications" section
    format = ["date", "journal", "authors", "title"]
    #If you don't want to group publications, comment the line below by adding # at the beginning
    types = [ "Books", "Articles"]

    [[params.publication.list]]
        title = "Release It!: Design and Deploy Production-Ready Software"
        authors = "Michael T. Nygard"
        date = "2007"
        link = "https://www.amazon.com/Release-Production-Ready-Software-Pragmatic-Programmers/dp/0978739213"
        type = "Books"

    [[params.publication.list]]
        title = "Ansible: Up and Running"
        authors = "Rene Moser, Lorin Hochstein"
        date = "2017"
        link = "https://www.oreilly.com/library/view/ansible-up-and/9781491979792"
        type = "Books"

    [[params.publication.list]]
        title = "Site Reliability Engineering"
        authors = "Edited by Betsy Beyer, Chris Jones, Jennifer Petoff and Niall Richard Murphy"
        date = "2017"
        link = "https://landing.google.com/sre/books"
        type = "Books"

    [[params.publication.list]]
        title = "Effective DevOps. Building a Culture of Collaboration, Affinity, and Tooling at Scale"
        authors = "Jennifer Davis, Ryn Daniels"
        date = "2016"
        link = "http://shop.oreilly.com/product/0636920039846.do"
        type = "Books"

    [[params.publication.list]]
        title = "Операционная система UNIX"
        authors = "Робачевский А. М."
        date = "2002"
        link = "http://muff.kiev.ua/files/books/OS_UNIX_RUS.pdf"
        type = "Books"

    [[params.publication.list]]
        title = "Linux Performance Analysis in 60,000 Milliseconds"
        journal = "Netflix Technology Blog"
        link = "https://medium.com/netflix-techblog/linux-performance-analysis-in-60-000-milliseconds-accc10403c55"
        type = "Articles"

    [[params.publication.list]]
        title = "Nomad - our experiences and best practices"
        authors = "Inga Feick"
        journal = "Trivago Tech Blog"
        link = "https://tech.trivago.com/2019/01/25/nomad-our-experiences-and-best-practices"
        type = "Articles"

    [[params.publication.list]]
        title = "24 sysadmin job interview questions you should know"
        authors = "DirectedSoul"
        journal = "RedHat DirectedSoul Blog"
        link = "https://opensource.com/article/19/7/sysadmin-job-interview-questions?utm_medium=email&utm_source=topic+optin&utm_campaign=awareness&utm_content=20190729+sysops+nl&mkt_tok=eyJpIjoiTlROa056Wm1PVFE1WVdFMyIsInQiOiJQckgwUTVVVThNR2hIMHlkVlN5QStNQXVkeGRcL3hFczVEWThLS21QOWduXC83Z0F4VlFJczV3XC93b2JTRmx2OVBOT2U0c05xWHJVT1F4cGU2UmJmSkZwOE5pOWpkR2k0MUp1eWxPWUxBb2gwZ0NlYTZsRURhdzA1NVV5RGhnZHpmOSJ9"
        type = "Articles"

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Reading"
        [[params.hobby.list]]		
		    hobby = "Cycling"
        [[params.hobby.list]]		
		    hobby = "Running"